### ISSUE TITLE
Allow notifications that don't require interaction

### ISSUE THREAD

**Issue by jonathanmv** [kyan001/ChromeMyExtens#2]
Hi, thanks a lot for your extension. I love how simple and fast it is, however I get annoyed by the fact that I need to manually dismiss the notification.

I found that you [hard coded](https://github.com/kyan001/WebExtensions/blob/master/ChromeExt_Timer25/Timer25/options.js#L98) `requireInteraction` which makes the notification always visible unless the user closes it. I tend not to use the mouse, it's actually far from my reach so I need to put a lot of effort to close the notification.

It's also annoying that for mac there's no easy way to dismiss notifications from the keyboard. 

So I would highly appreciate if you could add that feature. I was going to submit a pr but didn't do so due to the internationalization. The code should work pretty much as the option to play a sound.

Thank again. I hope other people find it as helpful as I do.

**Comment by kyan001** [comment]
Hi @jonathanmv ,

Thanks for you feedback.

The reason I set `requireInteraction` to `true`, is when my focus is not on my screen, and if the notification dismissed automatically, it tooks me a long time to realize the timer I set is done.

I do think your case is a good example for why we need this feature. I will add it in the next version, maybe you could get the update in few days. My plan is to add an option in option page, just like "play a sound" do.

Thanks again for your feedback and advise. Glad to know someone like this extension.

**Comment by kyan001** [comment]
@jonathanmv 

Now this feature is online. Please update your extension to `1.12.1`, and see if this is what you want.

**Comment by jonathanmv** [comment]
Ohhh man! I love it. Thanks a lot. That's exactly what I was requesting 👍 
I can also see people using permanent notification.

**Comment by jonathanmv** [comment]
I wanted to leave a review but the Review System is kind of down
![image](https://user-images.githubusercontent.com/86024/80861819-2d742180-8c71-11ea-88cb-e2432e43beea.png)

I'll post it once it's available again
